[workspace]
dependencies_update = false
changelog_update = true
git_release_enable = true
git_tag_enable = true

[[package]]
name = "tsukai-manifest"
version_group = "tsukai"

[[package]]
name = "tsukai-manifest-cli"
version_group = "tsukai"
